//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Darts_League
{
    using System;
    using System.Collections.Generic;
    
    public partial class DartType
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public int Weight { get; set; }
        public string Stems { get; set; }
        public string Flights { get; set; }
        public int PlayersId { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
