//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Darts_League
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DartsdatabaseEntities : DbContext
    {
        public DartsdatabaseEntities()
            : base("name=DartsdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DartType> DartTypes { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Standings> Standings { get; set; }
    }
}
